version: "2"

services:
    build:
        image: gradle:7-jdk11
        volumes:
            - .:/ATL_Incremental
        command: gradle build --no-daemon --stacktrace
        working_dir: /ATL_Incremental
        user: gradle

    run:
        image: openjdk:11-jre-slim
        volumes:
            - ../../:/app
        working_dir: /app
        command: java -jar /app/solutions/ATL_Incremental/build/libs/ATL_Incremental-all.jar
        environment:
            - RunIndex
            - Tool
            - Scenario
            - Sequences
            - Model
            - ModelPath
            - JAVA_OPTS=-Xms4g
            - RUNS_IN_CONTAINER=1
